<?php

/**
 * @var \Mage4\Appointment\Block\Display $block
 */
?>
<h3><?= __('Appointment Form') ?></h3>
<table>
	<tr>
		<th><?= __('ID') ?></th>
		<th><?= __('Name') ?></th>
		<th><?= __('Email') ?></th>
		<th><?= __('Phone') ?></th>
		<th><?= __('Comment') ?></th>
        <th><?= __('Date') ?></th>
        <th><?= __('Store') ?></th>
		<th><?= __('Created At') ?></th>
	</tr>
    <?php foreach ($block->getContactCollection() as $key=>$post){ ?>
    <tr>
    	<td><?= $post['id'] ?></td>
    	<td><?= $post['name'] ?></td>
    	<td><?= $post['email'] ?></td>
    	<td><?= $post['phone'] ?></td>
    	<td><?= $post['comment'] ?></td>
        <td><?= $post['date'] ?></td>
        <td><?= $post['store'] ?></td>
    	<td><?= $post['created_at'] ?></td>
    </tr>
    <?php } ?>
</table>
