<?php
/** @var InquiryForm $block */
$occupationOptions = $block->getOccupationOptions();
$activitiesoptions = $block->getActivitiesOptions();

use Mage4\Inquiry\Block\InquiryForm;

?>

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $block->getItems() ?>" method="post"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('User Information Form')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label"
                                   for="title"><span><?= $block->escapeHtmlAttr(__('Date of Birth')) ?></span></label>
                            <div class="control">
                                <input name="dob" id="dob" title="Date of Birth" value="" class="date"
                                       type="date" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label"
                                   for="title"><span><?= $block->escapeHtmlAttr(__('Occupation')) ?></span></label>
                            <div class="control">
                                <select name="occupation" id="occupation" title="occupation" value="" class="input-text"
                                        data-validate="{required:true}">
                                    <?php foreach ($occupationOptions as $key => $value): ?>
                                        <option value="<?= $key ?>"><?= $value ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label"
                                   for="activities"><span><?= $block->escapeHtmlAttr(__('Activities')) ?></span></label>
                            <div class="control">
                                <select name="activities[]" id="activities" title="activities" value=""
                                        class="input-text" data-validate="{required:true}" multiple>
                                    <?php foreach ($activitiesoptions as $key => $value): ?>
                                        <option value="<?= $key ?>"><?= $value ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
    </div>
</div>
</fieldset>
</fieldset>
<div class="actions-toolbar">
    <div class="primary">
        <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                escapeHtmlAttr(__('Save')) ?></span></button>
    </div>
</div>
</form>
</div>
</div>
